--- # H2 in-memory database configuration
spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    driverClassName:  org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled:  true
server:
  port: 8090